GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "first_name": "Jorge Pablo",
    "last_name": "Salomon Buenavista",
    "email" : "salosalomon@gmail.com",
    "password": "MyPassword123"
    
}
###


###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "first_name": "Susana Lizeth",
    "last_name": "Jorge Cruz",
    "email" : "jorgecruzsusana30@gmail.com",
    "password": "MyPassword123"
    
}
###


PUT http://localhost:3000/users/2
Content-Type: application/json

{
    "first_name": "Susana Lizeth",
    "last_name": "Jorge Cruz",
    "email" : "jorgecruzsusana@gmail.com"
    
}

###
DELETE http://localhost:3000/users/2


###
### Obtener todos los pokemones
GET http://localhost:3000/pokemons
Content-Type: application/json

###

### Obtener un Pokémon por ID
GET http://localhost:3000/pokemons/2
Content-Type: application/json

###

### Obtener 3 Pokemones aleatorios
GET http://localhost:3000/pokemons/play
Content-Type: application/json

###

### Crear un nuevo Pokémon
POST http://localhost:3000/pokemons
Content-Type: application/json

{
  "name": "Pikachu",
  "image": "https://example.com/pikachu.png"
}

###

### Actualizar un Pokémon existente
PUT http://localhost:3000/pokemons/1
Content-Type: application/json

{
  "name": "Raichu",
  "image": "https://example.com/raichu.png"
}

###

### Eliminar un Pokémon
DELETE http://localhost:3000/pokemons/1
Content-Type: application/json
